In [1]:
import numpy as np

In [2]:
print(dir(np
         ))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', '_numpy_tester', 'abs'

In [3]:
arr=np.array([1,2,3,4
             
             ])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr1=np.array([[1,2,3,4]])

In [7]:
np.size(arr)

4

In [8]:
np.shape(arr)

(4,)

In [9]:
np.shape(arr1)

(1, 4)

In [10]:
l=[1,2,4]

In [11]:
l*2

[1, 2, 4, 1, 2, 4]

In [12]:
l**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
arr1**2

array([[ 1,  4,  9, 16]], dtype=int32)

In [14]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [15]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [16]:
arr1=np.array([[1,2,3,4],
              [5,6,7,8]
              ])

In [17]:
np.shape(arr1)

(2, 4)

In [18]:
np.size(arr1)

8

In [19]:
arr.T

array([1, 2, 3, 4])

In [20]:
arr1.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [21]:
arr=np.arange(1,21)

In [22]:
np.shape(arr)

(20,)

In [23]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
np.reshape(arr,(10,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [96]:
np.arange(21,41).reshape((10,2),order="F")

array([[21, 31],
       [22, 32],
       [23, 33],
       [24, 34],
       [25, 35],
       [26, 36],
       [27, 37],
       [28, 38],
       [29, 39],
       [30, 40]])

In [52]:
arr1=np.arange(1,10001)

In [53]:
np.shape(arr1)

(10000,)

In [54]:
arr1[997]

998

In [55]:
arr1=np.arange(10000).reshape(100,100)

In [56]:
np.shape(arr1)

(100, 100)

In [63]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a*b)
print(sum(a*b))#vector multiplication or element wise multiplication

[ 4 10 18]
32


In [60]:
a.dot(b)#matrix multiplication

32

In [61]:
print(np.dot.__doc__)

dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).

    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.

    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.

    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.

    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::

        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : ndarray, optional
        Output argument. This must have the exact kind that would 

In [66]:
a=np.array([[1,2,3],[5,6,7]])

In [69]:
b=np.array([[1,2],[3,4],[5,6]])

In [70]:
a@b

array([[22, 28],
       [58, 76]])

In [71]:
a.dot(b)

array([[22, 28],
       [58, 76]])

In [72]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [73]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
a[1,1]

6

In [80]:
#find the sum of first column of matrix b
b[:,0]

array([1, 3, 5])

In [81]:
sum(b[:,0])#Efficient method

9

In [82]:
b[0,0]+b[1,0]+b[2,0]

9

In [86]:
arr=np.linspace(1,100,300)

In [87]:
arr

array([  1.        ,   1.33110368,   1.66220736,   1.99331104,
         2.32441472,   2.65551839,   2.98662207,   3.31772575,
         3.64882943,   3.97993311,   4.31103679,   4.64214047,
         4.97324415,   5.30434783,   5.63545151,   5.96655518,
         6.29765886,   6.62876254,   6.95986622,   7.2909699 ,
         7.62207358,   7.95317726,   8.28428094,   8.61538462,
         8.94648829,   9.27759197,   9.60869565,   9.93979933,
        10.27090301,  10.60200669,  10.93311037,  11.26421405,
        11.59531773,  11.9264214 ,  12.25752508,  12.58862876,
        12.91973244,  13.25083612,  13.5819398 ,  13.91304348,
        14.24414716,  14.57525084,  14.90635452,  15.23745819,
        15.56856187,  15.89966555,  16.23076923,  16.56187291,
        16.89297659,  17.22408027,  17.55518395,  17.88628763,
        18.2173913 ,  18.54849498,  18.87959866,  19.21070234,
        19.54180602,  19.8729097 ,  20.20401338,  20.53511706,
        20.86622074,  21.19732441,  21.52842809,  21.85

In [88]:
np.size(arr)

300

In [93]:
b=np.random.random_sample((3,5))

In [94]:
b

array([[0.99151952, 0.04071505, 0.53635783, 0.61463046, 0.89581123],
       [0.09754682, 0.1856105 , 0.27919702, 0.90645696, 0.80512197],
       [0.97165997, 0.67745904, 0.45850214, 0.27790266, 0.64056887]])

In [97]:
b+1

array([[1.99151952, 1.04071505, 1.53635783, 1.61463046, 1.89581123],
       [1.09754682, 1.1856105 , 1.27919702, 1.90645696, 1.80512197],
       [1.97165997, 1.67745904, 1.45850214, 1.27790266, 1.64056887]])

In [98]:
b*2

array([[1.98303905, 0.0814301 , 1.07271565, 1.22926091, 1.79162246],
       [0.19509364, 0.371221  , 0.55839404, 1.81291392, 1.61024394],
       [1.94331994, 1.35491808, 0.91700428, 0.55580532, 1.28113774]])

In [99]:
b**2

array([[0.98311097, 0.00165772, 0.28767972, 0.3777706 , 0.80247776],
       [0.00951538, 0.03445126, 0.07795098, 0.82166422, 0.64822139],
       [0.94412309, 0.45895075, 0.21022421, 0.07722989, 0.41032848]])

In [105]:
a=np.linspace(1,10,15).reshape(3,5)

In [106]:
a

array([[ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857],
       [ 4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429],
       [ 7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]])

In [107]:
b+a

array([[ 1.99151952,  1.68357219,  2.82207211,  3.54320188,  4.4672398 ],
       [ 4.31183254,  5.04275336,  5.77919702,  7.0493141 ,  7.59083626],
       [ 8.4002314 ,  8.74888761,  9.17278785,  9.63504552, 10.64056887]])

In [109]:
b.min(axis=0)#this will give the minimum element of the each columns

array([0.09754682, 0.04071505, 0.27919702, 0.27790266, 0.64056887])

In [110]:
b.min(axis=1)#this will give the minimum element of the each rows

array([0.04071505, 0.09754682, 0.27790266])

In [114]:
a=np.arange(10).reshape(2,5)

In [115]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [116]:
a.cumsum(axis=0)#cumulative sum of the each column

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13]], dtype=int32)

In [117]:
a.cumsum(axis=1)#cumulative sum of each rows

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35]], dtype=int32)

In [122]:
b.sum(axis=1
     )

array([3.07903409, 2.27393327, 3.02609268])

In [123]:
a=np.linspace(1,100,200,endpoint=True)

In [124]:
a

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34